name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug SSH Connection
        run: |
          # Update known_hosts
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

          # Debugging output: Print known_hosts file after updating
          cat ~/.ssh/known_hosts

          # Debugging output: Attempt an SSH connection
          ssh -i <(echo "${{ secrets.EC2_SSH_KEY }}") -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.HOST_DNS }} 'bash /home/ec2-user/travos-trust-app/deploy_script.sh'
