name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/private-key.pem
          chmod 400 ~/.ssh/private-key.pem
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

      - name: Set execute permission for deploy script
        run: chmod +x $GITHUB_WORKSPACE/deploy_script.sh

      - name: Upload and Execute Deploy Script on EC2
        run: |
          scp -o ConnectTimeout=60 -i ~/.ssh/private-key.pem $GITHUB_WORKSPACE/deploy_script.sh ec2-user@${{ secrets.HOST_DNS }}:/home/ec2-user/travos/travos-trust-app/
          ssh -o ConnectTimeout=60 -i ~/.ssh/private-key.pem ec2-user@${{ secrets.HOST_DNS }} 'sudo bash /home/ec2-user/travos/travos-trust-app/deploy_script.sh'
