name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Build Frontend
      run: |
        cd frontend
        npm run build

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Python Dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Deploy to EC2
      run: |
        ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts
        scp -r frontend/build ${{ secrets.REMOTE_USER }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}/frontend
        scp -r backend ${{ secrets.REMOTE_USER }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}/backend

        # Restart Gunicorn (Flask)
        sudo systemctl restart gunicorn

        # Restart Frontend Service
        sudo systemctl restart frontend

        # Restart Backend Service
        sudo systemctl restart backend

        # Restart Nginx
        sudo systemctl restart nginx
